import { IHomevsAway } from './../Model/home.vs.away.model';
import { Component, OnInit } from '@angular/core';
import { IMatch } from '../Model/match.detail.model';

@Component({
  selector: 'app-football',
  templateUrl: './football.component.html',
  styleUrls: ['./football.component.css']
})
export class FootballComponent implements OnInit {

  private homevsaway: IHomevsAway;
  private firstVSsecond: IMatch[];
  private firstLastMatch: IMatch[];
  private secondLastMatch: IMatch[];
  HomevsAway = {
    "firstTeam_VS_secondTeam": [
      {
        "match_id": "367105",
        "country_id": "169",
        "country_name": "England",
        "league_id": "62",
        "league_name": "Premier League",
        "match_date": "2019-01-03",
        "match_status": "FT",
        "match_time": "20:00",
        "match_hometeam_name": "Manchester City",
        "match_hometeam_score": "2",
        "match_awayteam_name": "Liverpool",
        "match_awayteam_score": "1",
        "match_hometeam_halftime_score": "1",
        "match_awayteam_halftime_score": "0",
        "match_live": "1"
      },
      {
        "match_id": "356753",
        "country_id": "169",
        "country_name": "England",
        "league_id": "62",
        "league_name": "Premier League",
        "match_date": "2018-10-07",
        "match_status": "FT",
        "match_time": "17:30",
        "match_hometeam_name": "Liverpool",
        "match_hometeam_score": "0",
        "match_awayteam_name": "Manchester City",
        "match_awayteam_score": "0",
        "match_hometeam_halftime_score": "0",
        "match_awayteam_halftime_score": "0",
        "match_live": "1"
      },
      {
        "match_id": "297509",
        "country_id": "168",
        "country_name": "International",
        "league_id": "1772",
        "league_name": "Champions Cup",
        "match_date": "2018-07-26",
        "match_status": "FT",
        "match_time": "02:05",
        "match_hometeam_name": "Manchester City",
        "match_hometeam_score": "1",
        "match_awayteam_name": "Liverpool",
        "match_awayteam_score": "2",
        "match_hometeam_halftime_score": "0",
        "match_awayteam_halftime_score": "0",
        "match_live": "1"
      },
      {
        "match_id": "273800",
        "country_id": "163",
        "country_name": "Champions League",
        "league_id": "996",
        "league_name": "Quarter Finals",
        "match_date": "2018-04-10",
        "match_status": "FT",
        "match_time": "19:45",
        "match_hometeam_name": "Manchester City",
        "match_hometeam_score": "1",
        "match_awayteam_name": "Liverpool",
        "match_awayteam_score": "2",
        "match_hometeam_halftime_score": "1",
        "match_awayteam_halftime_score": "0",
        "match_live": "1"
      },
      {
        "match_id": "273389",
        "country_id": "163",
        "country_name": "Champions League",
        "league_id": "996",
        "league_name": "Quarter Finals",
        "match_date": "2018-04-04",
        "match_status": "FT",
        "match_time": "19:45",
        "match_hometeam_name": "Liverpool",
        "match_hometeam_score": "3",
        "match_awayteam_name": "Manchester City",
        "match_awayteam_score": "0",
        "match_hometeam_halftime_score": "3",
        "match_awayteam_halftime_score": "0",
        "match_live": "1"
      },
      {
        "match_id": "246940",
        "country_id": "169",
        "country_name": "England",
        "league_id": "62",
        "league_name": "Premier League",
        "match_date": "2018-01-14",
        "match_status": "FT",
        "match_time": "17:00",
        "match_hometeam_name": "Liverpool",
        "match_hometeam_score": "4",
        "match_awayteam_name": "Manchester City",
        "match_awayteam_score": "3",
        "match_hometeam_halftime_score": "1",
        "match_awayteam_halftime_score": "1",
        "match_live": "1"
      },
      {
        "match_id": "207503",
        "country_id": "169",
        "country_name": "England",
        "league_id": "62",
        "league_name": "Premier League",
        "match_date": "2017-09-09",
        "match_status": "FT",
        "match_time": "13:30",
        "match_hometeam_name": "Manchester City",
        "match_hometeam_score": "5",
        "match_awayteam_name": "Liverpool",
        "match_awayteam_score": "0",
        "match_hometeam_halftime_score": "2",
        "match_awayteam_halftime_score": "0",
        "match_live": "1"
      },
      {
        "match_id": "161488",
        "country_id": "169",
        "country_name": "England",
        "league_id": "62",
        "league_name": "Premier League",
        "match_date": "2017-03-19",
        "match_status": "FT",
        "match_time": "17:30",
        "match_hometeam_name": "Manchester City",
        "match_hometeam_score": "1",
        "match_awayteam_name": "Liverpool",
        "match_awayteam_score": "1",
        "match_hometeam_halftime_score": "",
        "match_awayteam_halftime_score": "",
        "match_live": "1"
      },
      {
        "match_id": "135085",
        "country_id": "169",
        "country_name": "England",
        "league_id": "62",
        "league_name": "Premier League",
        "match_date": "2016-12-31",
        "match_status": "FT",
        "match_time": "18:30",
        "match_hometeam_name": "Liverpool",
        "match_hometeam_score": "1",
        "match_awayteam_name": "Manchester City",
        "match_awayteam_score": "0",
        "match_hometeam_halftime_score": "",
        "match_awayteam_halftime_score": "",
        "match_live": "1"
      },
      {
        "match_id": "63318",
        "country_id": "169",
        "country_name": "England",
        "league_id": "62",
        "league_name": "Premier League",
        "match_date": "2016-03-02",
        "match_status": "FT",
        "match_time": "20:00",
        "match_hometeam_name": "Liverpool",
        "match_hometeam_score": "3",
        "match_awayteam_name": "Manchester City",
        "match_awayteam_score": "0",
        "match_hometeam_halftime_score": "",
        "match_awayteam_halftime_score": "",
        "match_live": "1"
      }
    ],
    "firstTeam_lastResults": [
      {
        "match_id": "414050",
        "country_id": "169",
        "country_name": "England",
        "league_id": "69",
        "league_name": "FA Cup",
        "match_date": "2019-05-18",
        "match_status": "FT",
        "match_time": "16:00",
        "match_hometeam_name": "Manchester City",
        "match_hometeam_score": "6",
        "match_awayteam_name": "Watford",
        "match_awayteam_score": "0",
        "match_hometeam_halftime_score": "2",
        "match_awayteam_halftime_score": "0",
        "match_live": "1"
      },
      {
        "match_id": "412015",
        "country_id": "169",
        "country_name": "England",
        "league_id": "62",
        "league_name": "Premier League",
        "match_date": "2019-05-12",
        "match_status": "FT",
        "match_time": "14:00",
        "match_hometeam_name": "Brighton &amp; Hove Albion",
        "match_hometeam_score": "1",
        "match_awayteam_name": "Manchester City",
        "match_awayteam_score": "4",
        "match_hometeam_halftime_score": "1",
        "match_awayteam_halftime_score": "2",
        "match_live": "1"
      },
      {
        "match_id": "410018",
        "country_id": "169",
        "country_name": "England",
        "league_id": "62",
        "league_name": "Premier League",
        "match_date": "2019-05-06",
        "match_status": "FT",
        "match_time": "19:00",
        "match_hometeam_name": "Manchester City",
        "match_hometeam_score": "1",
        "match_awayteam_name": "Leicester City",
        "match_awayteam_score": "0",
        "match_hometeam_halftime_score": "0",
        "match_awayteam_halftime_score": "0",
        "match_live": "1"
      },
      {
        "match_id": "410726",
        "country_id": "169",
        "country_name": "England",
        "league_id": "76",
        "league_name": "Premier L. U21:: div. 1",
        "match_date": "2019-04-29",
        "match_status": "FT",
        "match_time": "18:00",
        "match_hometeam_name": "Manchester City",
        "match_hometeam_score": "3",
        "match_awayteam_name": "Swansea City",
        "match_awayteam_score": "1",
        "match_hometeam_halftime_score": "0",
        "match_awayteam_halftime_score": "0",
        "match_live": "1"
      },
      {
        "match_id": "407136",
        "country_id": "169",
        "country_name": "England",
        "league_id": "62",
        "league_name": "Premier League",
        "match_date": "2019-04-28",
        "match_status": "FT",
        "match_time": "15:05",
        "match_hometeam_name": "Burnley",
        "match_hometeam_score": "0",
        "match_awayteam_name": "Manchester City",
        "match_awayteam_score": "1",
        "match_hometeam_halftime_score": "0",
        "match_awayteam_halftime_score": "0",
        "match_live": "1"
      },
      {
        "match_id": "405270",
        "country_id": "169",
        "country_name": "England",
        "league_id": "62",
        "league_name": "Premier League",
        "match_date": "2019-04-24",
        "match_status": "FT",
        "match_time": "21:00",
        "match_hometeam_name": "Manchester United",
        "match_hometeam_score": "0",
        "match_awayteam_name": "Manchester City",
        "match_awayteam_score": "2",
        "match_hometeam_halftime_score": "0",
        "match_awayteam_halftime_score": "0",
        "match_live": "1"
      },
      {
        "match_id": "403899",
        "country_id": "169",
        "country_name": "England",
        "league_id": "62",
        "league_name": "Premier League",
        "match_date": "2019-04-20",
        "match_status": "FT",
        "match_time": "13:30",
        "match_hometeam_name": "Manchester City",
        "match_hometeam_score": "1",
        "match_awayteam_name": "Tottenham Hotspur",
        "match_awayteam_score": "0",
        "match_hometeam_halftime_score": "1",
        "match_awayteam_halftime_score": "0",
        "match_live": "1"
      },
      {
        "match_id": "402428",
        "country_id": "163",
        "country_name": "Champions League",
        "league_id": "996",
        "league_name": "Quarter Finals",
        "match_date": "2019-04-17",
        "match_status": "FT",
        "match_time": "21:00",
        "match_hometeam_name": "Manchester City",
        "match_hometeam_score": "4",
        "match_awayteam_name": "Tottenham Hotspur",
        "match_awayteam_score": "3",
        "match_hometeam_halftime_score": "3",
        "match_awayteam_halftime_score": "2",
        "match_live": "1"
      },
      {
        "match_id": "405999",
        "country_id": "169",
        "country_name": "England",
        "league_id": "76",
        "league_name": "Premier L. U21:: div. 1",
        "match_date": "2019-04-15",
        "match_status": "FT",
        "match_time": "18:00",
        "match_hometeam_name": "Blackburn Rovers",
        "match_hometeam_score": "3",
        "match_awayteam_name": "Manchester City",
        "match_awayteam_score": "1",
        "match_hometeam_halftime_score": "0",
        "match_awayteam_halftime_score": "0",
        "match_live": "1"
      },
      {
        "match_id": "401496",
        "country_id": "169",
        "country_name": "England",
        "league_id": "62",
        "league_name": "Premier League",
        "match_date": "2019-04-14",
        "match_status": "FT",
        "match_time": "15:05",
        "match_hometeam_name": "Crystal Palace",
        "match_hometeam_score": "1",
        "match_awayteam_name": "Manchester City",
        "match_awayteam_score": "3",
        "match_hometeam_halftime_score": "0",
        "match_awayteam_halftime_score": "1",
        "match_live": "1"
      }
    ],
    "secondTeam_lastResults": [
      {
        "match_id": "408253",
        "country_id": "163",
        "country_name": "Champions League",
        "league_id": "1068",
        "league_name": "Final",
        "match_date": "2019-06-01",
        "match_status": "FT",
        "match_time": "21:00",
        "match_hometeam_name": "Tottenham Hotspur",
        "match_hometeam_score": "0",
        "match_awayteam_name": "Liverpool",
        "match_awayteam_score": "2",
        "match_hometeam_halftime_score": "0",
        "match_awayteam_halftime_score": "1",
        "match_live": "1"
      },
      {
        "match_id": "412020",
        "country_id": "169",
        "country_name": "England",
        "league_id": "62",
        "league_name": "Premier League",
        "match_date": "2019-05-12",
        "match_status": "FT",
        "match_time": "16:00",
        "match_hometeam_name": "Liverpool",
        "match_hometeam_score": "2",
        "match_awayteam_name": "Wolverhampton Wanderers",
        "match_awayteam_score": "0",
        "match_hometeam_halftime_score": "1",
        "match_awayteam_halftime_score": "0",
        "match_live": "1"
      },
      {
        "match_id": "410161",
        "country_id": "163",
        "country_name": "Champions League",
        "league_id": "1069",
        "league_name": "Semi Finals",
        "match_date": "2019-05-07",
        "match_status": "FT",
        "match_time": "19:00",
        "match_hometeam_name": "Liverpool",
        "match_hometeam_score": "4",
        "match_awayteam_name": "Barcelona",
        "match_awayteam_score": "0",
        "match_hometeam_halftime_score": "1",
        "match_awayteam_halftime_score": "0",
        "match_live": "1"
      },
      {
        "match_id": "410000",
        "country_id": "169",
        "country_name": "England",
        "league_id": "62",
        "league_name": "Premier League",
        "match_date": "2019-05-04",
        "match_status": "FT",
        "match_time": "18:45",
        "match_hometeam_name": "Newcastle United",
        "match_hometeam_score": "2",
        "match_awayteam_name": "Liverpool",
        "match_awayteam_score": "3",
        "match_hometeam_halftime_score": "1",
        "match_awayteam_halftime_score": "2",
        "match_live": "1"
      },
      {
        "match_id": "408641",
        "country_id": "163",
        "country_name": "Champions League",
        "league_id": "1069",
        "league_name": "Semi Finals",
        "match_date": "2019-05-01",
        "match_status": "FT",
        "match_time": "19:00",
        "match_hometeam_name": "Barcelona",
        "match_hometeam_score": "3",
        "match_awayteam_name": "Liverpool",
        "match_awayteam_score": "0",
        "match_hometeam_halftime_score": "1",
        "match_awayteam_halftime_score": "0",
        "match_live": "1"
      },
      {
        "match_id": "405585",
        "country_id": "169",
        "country_name": "England",
        "league_id": "62",
        "league_name": "Premier League",
        "match_date": "2019-04-26",
        "match_status": "FT",
        "match_time": "21:00",
        "match_hometeam_name": "Liverpool",
        "match_hometeam_score": "5",
        "match_awayteam_name": "Huddersfield Town",
        "match_awayteam_score": "0",
        "match_hometeam_halftime_score": "3",
        "match_awayteam_halftime_score": "0",
        "match_live": "1"
      },
      {
        "match_id": "404352",
        "country_id": "169",
        "country_name": "England",
        "league_id": "62",
        "league_name": "Premier League",
        "match_date": "2019-04-21",
        "match_status": "FT",
        "match_time": "17:00",
        "match_hometeam_name": "Cardiff City",
        "match_hometeam_score": "0",
        "match_awayteam_name": "Liverpool",
        "match_awayteam_score": "2",
        "match_hometeam_halftime_score": "0",
        "match_awayteam_halftime_score": "0",
        "match_live": "1"
      },
      {
        "match_id": "402427",
        "country_id": "163",
        "country_name": "Champions League",
        "league_id": "996",
        "league_name": "Quarter Finals",
        "match_date": "2019-04-17",
        "match_status": "FT",
        "match_time": "21:00",
        "match_hometeam_name": "FC Porto",
        "match_hometeam_score": "1",
        "match_awayteam_name": "Liverpool",
        "match_awayteam_score": "4",
        "match_hometeam_halftime_score": "0",
        "match_awayteam_halftime_score": "1",
        "match_live": "1"
      },
      {
        "match_id": "401497",
        "country_id": "169",
        "country_name": "England",
        "league_id": "62",
        "league_name": "Premier League",
        "match_date": "2019-04-14",
        "match_status": "FT",
        "match_time": "17:30",
        "match_hometeam_name": "Liverpool",
        "match_hometeam_score": "2",
        "match_awayteam_name": "Chelsea",
        "match_awayteam_score": "0",
        "match_hometeam_halftime_score": "0",
        "match_awayteam_halftime_score": "0",
        "match_live": "1"
      },
      {
        "match_id": "394813",
        "country_id": "163",
        "country_name": "Champions League",
        "league_id": "996",
        "league_name": "Quarter Finals",
        "match_date": "2019-04-09",
        "match_status": "FT",
        "match_time": "19:00",
        "match_hometeam_name": "Liverpool",
        "match_hometeam_score": "2",
        "match_awayteam_name": "FC Porto",
        "match_awayteam_score": "0",
        "match_hometeam_halftime_score": "2",
        "match_awayteam_halftime_score": "0",
        "match_live": "1"
      }
    ]
  };
  constructor() { }

  ngOnInit() {
    this.firstVSsecond = this.HomevsAway.firstTeam_VS_secondTeam;
    this.firstLastMatch = this.HomevsAway.firstTeam_lastResults;
    this.secondLastMatch = this.HomevsAway.secondTeam_lastResults;
  }

}
